"""
.. module:: picontrol_server.codes
.. moduleauthor:: Julien Spronck
.. created:: March 2017

This module contains everything related to connection codes. When trying to
connect from the iOS app, it will require a connection code. This code will
be generated by the server and written into a file.

You can check the code by ssh'ing to the server and use the picontrol_server
command line tool.
"""

from config import config
import os

CONNECTION_CODE_FILE = os.path.expanduser(config.CONNECTION_CODE_FILE)

def get_connection_code():
    '''Returns the connection code written in CONNECTION_CODE_FILE. If the file
    does not exist, it will create a code and save it to file.

    Returns:
        str: the connection code.
    '''

    if not os.path.exists(CONNECTION_CODE_FILE):
        create_connection_code()
    with open(CONNECTION_CODE_FILE, 'r') as fil:
        return fil.read().strip()

def create_connection_code():
    '''Creates a connection code and saves it in CONNECTION_CODE_FILE.
    '''

    import string
    import random
    nchars = 6
    code = ''.join(random.choice(string.ascii_uppercase + string.digits)
                   for _ in range(nchars))
    with open(CONNECTION_CODE_FILE, 'w') as fil:
        fil.write(code)
